# Generated by hand for TanPit visibility switches

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("pits", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="VisibilitySetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("show_fill", models.BooleanField(default=True)),
                ("show_tanning", models.BooleanField(default=True)),
                ("show_drained", models.BooleanField(default=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
