# Generated by hand for TanPit visibility switches

from django.db import migrations, models


def create_singleton(apps, schema_editor):
    VisibilitySetting = apps.get_model("pits", "VisibilitySetting")
    # 全库唯一一版开关，默认三路全开（与旧行为一致：全部坑态可见）
    VisibilitySetting.objects.get_or_create(pk=1)


class Migration(migrations.Migration):
    dependencies = [
        ("pits", "0001_initial"),
    ]
    operations = [
        migrations.CreateModel(
            name="VisibilitySetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("show_fill", models.BooleanField(default=True)),
                ("show_tanning", models.BooleanField(default=True)),
                ("show_drained", models.BooleanField(default=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(create_singleton, migrations.RunPython.noop),
    ]
